apiVersion: 1

datasources:
  - name: Fixed-UID-testbed
    type: prometheus
    access: proxy
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m