// Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

//! Pluggable block-header authentication.
//!
//! A block reference is the BLAKE3 digest of the header *content*; the
//! authentication proof is a separate header field that never enters the
//! digest. This makes the block identity independent of the signature scheme,
//! so every consensus protocol can be run unchanged with any scheme listed in
//! [`BlockAuthenticationScheme`].
//!
//! Ed25519 (the default) keeps using the committee's identity key. Post-quantum
//! schemes are implemented behind [`PqSignatureScheme`]; each scheme is a
//! zero-sized marker type, and the dispatch enums are generated by the
//! `block_authentication_schemes!` macro at the bottom of this file. Adding a
//! scheme therefore means: implement the trait for a marker (one macro line
//! for the crates already wired here) and add one line to that macro call.

use std::{fmt, marker::PhantomData, str::FromStr};

use serde::{Deserialize, Deserializer, Serialize, Serializer, de};

use crate::crypto::{AsBytes, BlockDigest, PublicKey, SignatureBytes, Signer};

// ---------------------------------------------------------------------------
// Generic post-quantum scheme abstraction
// ---------------------------------------------------------------------------

/// A digital-signature scheme usable for block authentication.
///
/// Implementors are zero-sized marker types. Messages are always the 32-byte
/// block content digest. All encodings are the scheme's standard byte
/// encodings (FIPS 204 / FIPS 205).
pub trait PqSignatureScheme:
    Clone + Copy + fmt::Debug + PartialEq + Eq + Send + Sync + 'static
{
    /// Stable, lower-case, kebab-case identifier (CLI / YAML value).
    const NAME: &'static str;
    const PUBLIC_KEY_SIZE: usize;
    /// Size of the serialized private key material.
    const SECRET_KEY_SIZE: usize;
    const SIGNATURE_SIZE: usize;

    type SigningKey: Clone + Send + Sync;
    type VerifyingKey: Clone + Send + Sync;

    /// Deterministically derive a signing key from 32 bytes of seed material.
    fn keygen_from_seed(seed: &[u8; 32]) -> Self::SigningKey;
    fn signing_key_to_bytes(key: &Self::SigningKey) -> Vec<u8>;
    fn signing_key_from_bytes(bytes: &[u8]) -> Option<Self::SigningKey>;
    fn verifying_key(key: &Self::SigningKey) -> Self::VerifyingKey;
    fn verifying_key_to_bytes(key: &Self::VerifyingKey) -> Vec<u8>;
    fn verifying_key_from_bytes(bytes: &[u8]) -> Option<Self::VerifyingKey>;
    fn sign(key: &Self::SigningKey, message: &[u8]) -> Vec<u8>;
    fn verify(key: &Self::VerifyingKey, message: &[u8], signature: &[u8]) -> bool;
}

/// Private signing key of scheme `S`. Boxed so moving the wrapper does not
/// copy secret material around the stack.
pub struct PqSigner<S: PqSignatureScheme>(Box<S::SigningKey>);

/// Public verifying key of scheme `S`, kept in decoded form so the hot
/// verification path does not re-parse it.
pub struct PqPublicKey<S: PqSignatureScheme>(S::VerifyingKey);

/// Encoded signature of scheme `S`. Length is validated on construction; the
/// scheme parses it again during verification.
pub struct PqSignature<S: PqSignatureScheme>(Box<[u8]>, PhantomData<S>);

impl<S: PqSignatureScheme> PqSigner<S> {
    pub fn from_seed(seed: &[u8; 32]) -> Self {
        Self(Box::new(S::keygen_from_seed(seed)))
    }

    pub fn from_bytes(bytes: &[u8]) -> Result<Self, String> {
        if bytes.len() != S::SECRET_KEY_SIZE {
            return Err(format!(
                "invalid {} secret key length {} (expected {})",
                S::NAME,
                bytes.len(),
                S::SECRET_KEY_SIZE
            ));
        }
        S::signing_key_from_bytes(bytes)
            .map(|key| Self(Box::new(key)))
            .ok_or_else(|| format!("invalid {} secret key encoding", S::NAME))
    }

    pub fn to_bytes(&self) -> Vec<u8> {
        S::signing_key_to_bytes(&self.0)
    }

    pub fn public_key(&self) -> PqPublicKey<S> {
        PqPublicKey(S::verifying_key(&self.0))
    }

    pub fn sign(&self, message: &[u8; 32]) -> PqSignature<S> {
        let bytes = S::sign(&self.0, message);
        debug_assert_eq!(bytes.len(), S::SIGNATURE_SIZE);
        PqSignature(bytes.into_boxed_slice(), PhantomData)
    }
}

impl<S: PqSignatureScheme> PqPublicKey<S> {
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, String> {
        if bytes.len() != S::PUBLIC_KEY_SIZE {
            return Err(format!(
                "invalid {} public key length {} (expected {})",
                S::NAME,
                bytes.len(),
                S::PUBLIC_KEY_SIZE
            ));
        }
        S::verifying_key_from_bytes(bytes)
            .map(Self)
            .ok_or_else(|| format!("invalid {} public key encoding", S::NAME))
    }

    pub fn to_bytes(&self) -> Vec<u8> {
        S::verifying_key_to_bytes(&self.0)
    }

    pub fn verify(&self, message: &[u8; 32], signature: &PqSignature<S>) -> bool {
        S::verify(&self.0, message, &signature.0)
    }
}

impl<S: PqSignatureScheme> PqSignature<S> {
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, String> {
        if bytes.len() != S::SIGNATURE_SIZE {
            return Err(format!(
                "invalid {} signature length {} (expected {})",
                S::NAME,
                bytes.len(),
                S::SIGNATURE_SIZE
            ));
        }
        Ok(Self(bytes.into(), PhantomData))
    }

    pub fn as_bytes(&self) -> &[u8] {
        &self.0
    }
}

impl<S: PqSignatureScheme> Clone for PqSigner<S> {
    fn clone(&self) -> Self {
        Self(self.0.clone())
    }
}

impl<S: PqSignatureScheme> Clone for PqPublicKey<S> {
    fn clone(&self) -> Self {
        Self(self.0.clone())
    }
}

impl<S: PqSignatureScheme> Clone for PqSignature<S> {
    fn clone(&self) -> Self {
        Self(self.0.clone(), PhantomData)
    }
}

impl<S: PqSignatureScheme> PartialEq for PqPublicKey<S> {
    fn eq(&self, other: &Self) -> bool {
        self.to_bytes() == other.to_bytes()
    }
}
impl<S: PqSignatureScheme> Eq for PqPublicKey<S> {}

impl<S: PqSignatureScheme> PartialEq for PqSignature<S> {
    fn eq(&self, other: &Self) -> bool {
        self.0 == other.0
    }
}
impl<S: PqSignatureScheme> Eq for PqSignature<S> {}

impl<S: PqSignatureScheme> fmt::Debug for PqSigner<S> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}Signer(public_key={:?})", S::NAME, self.public_key())
    }
}

impl<S: PqSignatureScheme> fmt::Debug for PqPublicKey<S> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}Pk({})", S::NAME, hex::encode(&self.to_bytes()[..4]))
    }
}

impl<S: PqSignatureScheme> fmt::Debug for PqSignature<S> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}Sig({})", S::NAME, hex::encode(&self.0[..4]))
    }
}

impl<S: PqSignatureScheme> Serialize for PqSigner<S> {
    fn serialize<Ser: Serializer>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error> {
        serialize_bytes(&self.to_bytes(), serializer)
    }
}

impl<'de, S: PqSignatureScheme> Deserialize<'de> for PqSigner<S> {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let bytes = deserialize_bytes(deserializer, S::NAME, S::SECRET_KEY_SIZE)?;
        Self::from_bytes(&bytes).map_err(de::Error::custom)
    }
}

impl<S: PqSignatureScheme> Serialize for PqPublicKey<S> {
    fn serialize<Ser: Serializer>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error> {
        serialize_bytes(&self.to_bytes(), serializer)
    }
}

impl<'de, S: PqSignatureScheme> Deserialize<'de> for PqPublicKey<S> {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let bytes = deserialize_bytes(deserializer, S::NAME, S::PUBLIC_KEY_SIZE)?;
        Self::from_bytes(&bytes).map_err(de::Error::custom)
    }
}

impl<S: PqSignatureScheme> Serialize for PqSignature<S> {
    fn serialize<Ser: Serializer>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error> {
        serialize_bytes(&self.0, serializer)
    }
}

impl<'de, S: PqSignatureScheme> Deserialize<'de> for PqSignature<S> {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let bytes = deserialize_bytes(deserializer, S::NAME, S::SIGNATURE_SIZE)?;
        Self::from_bytes(&bytes).map_err(de::Error::custom)
    }
}

/// Hex string for human-readable formats (YAML), raw bytes otherwise (bincode).
fn serialize_bytes<S: Serializer>(bytes: &[u8], serializer: S) -> Result<S::Ok, S::Error> {
    if serializer.is_human_readable() {
        serializer.serialize_str(&hex::encode(bytes))
    } else {
        serializer.serialize_bytes(bytes)
    }
}

fn deserialize_bytes<'de, D: Deserializer<'de>>(
    deserializer: D,
    type_name: &'static str,
    expected_len: usize,
) -> Result<Vec<u8>, D::Error> {
    struct BytesVisitor {
        type_name: &'static str,
        expected_len: usize,
    }

    impl<'de> de::Visitor<'de> for BytesVisitor {
        type Value = Vec<u8>;

        fn expecting(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
            write!(
                formatter,
                "{} bytes of {} (raw or hex encoded)",
                self.expected_len, self.type_name
            )
        }

        fn visit_bytes<E: de::Error>(self, v: &[u8]) -> Result<Self::Value, E> {
            if v.len() != self.expected_len {
                return Err(E::custom(format!(
                    "invalid {} length {} (expected {})",
                    self.type_name,
                    v.len(),
                    self.expected_len
                )));
            }
            Ok(v.to_vec())
        }

        fn visit_byte_buf<E: de::Error>(self, v: Vec<u8>) -> Result<Self::Value, E> {
            self.visit_bytes(&v)
        }

        fn visit_str<E: de::Error>(self, v: &str) -> Result<Self::Value, E> {
            let decoded = hex::decode(v)
                .map_err(|e| E::custom(format!("invalid {} hex encoding: {e}", self.type_name)))?;
            self.visit_bytes(&decoded)
        }
    }

    let visitor = BytesVisitor {
        type_name,
        expected_len,
    };
    if deserializer.is_human_readable() {
        deserializer.deserialize_str(visitor)
    } else {
        deserializer.deserialize_bytes(visitor)
    }
}

/// Deterministic per-authority seed for benchmark and test key material.
/// Domain-separated by scheme so no two schemes share entropy.
pub fn benchmark_seed(scheme: BlockAuthenticationScheme, authority: u64) -> [u8; 32] {
    let mut hasher = blake3::Hasher::new_derive_key("starfish block authentication benchmark seed");
    hasher.update(scheme.name().as_bytes());
    hasher.update(&authority.to_le_bytes());
    hasher.finalize().into()
}

/// Expand a 32-byte seed into `output.len()` bytes of scheme-specific key
/// material.
fn expand_seed(scheme_name: &str, seed: &[u8; 32], output: &mut [u8]) {
    let mut hasher = blake3::Hasher::new_derive_key("starfish block authentication key expansion");
    hasher.update(scheme_name.as_bytes());
    hasher.update(seed);
    hasher.finalize_xof().fill(output);
}

// ---------------------------------------------------------------------------
// ML-DSA (FIPS 204) — RustCrypto `ml-dsa`
// ---------------------------------------------------------------------------

macro_rules! impl_ml_dsa_scheme {
    ($marker:ident, $params:ty, $name:literal, pk = $pk:literal, sig = $sig:literal) => {
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub struct $marker;

        impl PqSignatureScheme for $marker {
            const NAME: &'static str = $name;
            const PUBLIC_KEY_SIZE: usize = $pk;
            /// ML-DSA private keys are stored as their 32-byte seed (FIPS 204 §3.6.3).
            const SECRET_KEY_SIZE: usize = 32;
            const SIGNATURE_SIZE: usize = $sig;

            type SigningKey = ml_dsa::SigningKey<$params>;
            type VerifyingKey = ml_dsa::VerifyingKey<$params>;

            fn keygen_from_seed(seed: &[u8; 32]) -> Self::SigningKey {
                ml_dsa::SigningKey::<$params>::from_seed(&ml_dsa::Seed::from(*seed))
            }

            fn signing_key_to_bytes(key: &Self::SigningKey) -> Vec<u8> {
                key.to_seed().to_vec()
            }

            fn signing_key_from_bytes(bytes: &[u8]) -> Option<Self::SigningKey> {
                let seed: [u8; 32] = bytes.try_into().ok()?;
                Some(Self::keygen_from_seed(&seed))
            }

            fn verifying_key(key: &Self::SigningKey) -> Self::VerifyingKey {
                ml_dsa::Keypair::verifying_key(key)
            }

            fn verifying_key_to_bytes(key: &Self::VerifyingKey) -> Vec<u8> {
                key.encode().to_vec()
            }

            fn verifying_key_from_bytes(bytes: &[u8]) -> Option<Self::VerifyingKey> {
                let encoded = ml_dsa::EncodedVerifyingKey::<$params>::try_from(bytes).ok()?;
                Some(ml_dsa::VerifyingKey::<$params>::decode(&encoded))
            }

            fn sign(key: &Self::SigningKey, message: &[u8]) -> Vec<u8> {
                // Deterministic signing (FIPS 204 §5.2 with a fixed rnd), so
                // honest validators never produce two proofs for one digest.
                let signature: ml_dsa::Signature<$params> = ml_dsa::Signer::sign(key, message);
                signature.encode().to_vec()
            }

            fn verify(key: &Self::VerifyingKey, message: &[u8], signature: &[u8]) -> bool {
                let Ok(signature) = ml_dsa::Signature::<$params>::try_from(signature) else {
                    return false;
                };
                ml_dsa::Verifier::verify(key, message, &signature).is_ok()
            }
        }
    };
}

impl_ml_dsa_scheme!(
    MlDsa44,
    ml_dsa::MlDsa44,
    "ml-dsa-44",
    pk = 1_312,
    sig = 2_420
);
impl_ml_dsa_scheme!(
    MlDsa65,
    ml_dsa::MlDsa65,
    "ml-dsa-65",
    pk = 1_952,
    sig = 3_309
);
impl_ml_dsa_scheme!(
    MlDsa87,
    ml_dsa::MlDsa87,
    "ml-dsa-87",
    pk = 2_592,
    sig = 4_627
);

// ---------------------------------------------------------------------------
// SLH-DSA (FIPS 205) — RustCrypto `slh-dsa`
// ---------------------------------------------------------------------------

macro_rules! impl_slh_dsa_scheme {
    ($marker:ident, $params:ty, $name:literal, n = $n:literal, sig = $sig:literal) => {
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub struct $marker;

        impl PqSignatureScheme for $marker {
            const NAME: &'static str = $name;
            /// pk = PK.seed || PK.root
            const PUBLIC_KEY_SIZE: usize = 2 * $n;
            /// sk = SK.seed || SK.prf || PK.seed || PK.root
            const SECRET_KEY_SIZE: usize = 4 * $n;
            const SIGNATURE_SIZE: usize = $sig;

            type SigningKey = slh_dsa::SigningKey<$params>;
            type VerifyingKey = slh_dsa::VerifyingKey<$params>;

            fn keygen_from_seed(seed: &[u8; 32]) -> Self::SigningKey {
                // FIPS 205 Algorithm 21: keygen from (SK.seed, SK.prf, PK.seed).
                let mut material = [0u8; 3 * $n];
                expand_seed($name, seed, &mut material);
                let (sk_seed, rest) = material.split_at($n);
                let (sk_prf, pk_seed) = rest.split_at($n);
                slh_dsa::SigningKey::<$params>::slh_keygen_internal(sk_seed, sk_prf, pk_seed)
            }

            fn signing_key_to_bytes(key: &Self::SigningKey) -> Vec<u8> {
                key.to_vec()
            }

            fn signing_key_from_bytes(bytes: &[u8]) -> Option<Self::SigningKey> {
                slh_dsa::SigningKey::<$params>::try_from(bytes).ok()
            }

            fn verifying_key(key: &Self::SigningKey) -> Self::VerifyingKey {
                slh_dsa::signature::Keypair::verifying_key(key)
            }

            fn verifying_key_to_bytes(key: &Self::VerifyingKey) -> Vec<u8> {
                key.to_vec()
            }

            fn verifying_key_from_bytes(bytes: &[u8]) -> Option<Self::VerifyingKey> {
                slh_dsa::VerifyingKey::<$params>::try_from(bytes).ok()
            }

            fn sign(key: &Self::SigningKey, message: &[u8]) -> Vec<u8> {
                // `try_sign` is the deterministic variant (opt_rand = PK.seed).
                let signature: slh_dsa::Signature<$params> =
                    slh_dsa::signature::Signer::try_sign(key, message)
                        .expect("SLH-DSA signing is infallible for a valid key");
                signature.to_vec()
            }

            fn verify(key: &Self::VerifyingKey, message: &[u8], signature: &[u8]) -> bool {
                let Ok(signature) = slh_dsa::Signature::<$params>::try_from(signature) else {
                    return false;
                };
                slh_dsa::signature::Verifier::verify(key, message, &signature).is_ok()
            }
        }
    };
}

impl_slh_dsa_scheme!(
    SlhDsaSha2_128s,
    slh_dsa::Sha2_128s,
    "slh-dsa-sha2-128s",
    n = 16,
    sig = 7_856
);
impl_slh_dsa_scheme!(
    SlhDsaSha2_128f,
    slh_dsa::Sha2_128f,
    "slh-dsa-sha2-128f",
    n = 16,
    sig = 17_088
);
impl_slh_dsa_scheme!(
    SlhDsaSha2_192s,
    slh_dsa::Sha2_192s,
    "slh-dsa-sha2-192s",
    n = 24,
    sig = 16_224
);
impl_slh_dsa_scheme!(
    SlhDsaSha2_192f,
    slh_dsa::Sha2_192f,
    "slh-dsa-sha2-192f",
    n = 24,
    sig = 35_664
);
impl_slh_dsa_scheme!(
    SlhDsaSha2_256s,
    slh_dsa::Sha2_256s,
    "slh-dsa-sha2-256s",
    n = 32,
    sig = 29_792
);
impl_slh_dsa_scheme!(
    SlhDsaSha2_256f,
    slh_dsa::Sha2_256f,
    "slh-dsa-sha2-256f",
    n = 32,
    sig = 49_856
);

// ---------------------------------------------------------------------------
// Scheme registry: the single place where the list of schemes lives.
// ---------------------------------------------------------------------------

/// Generates every enum that must dispatch over the concrete post-quantum
/// schemes. `tag` is the byte prefix used in the binary encoding of
/// [`BlockAuthentication`]; tags are append-only (0 = none, 1 = Ed25519).
macro_rules! block_authentication_schemes {
    ($( $variant:ident($scheme:ty, $name:literal) = $tag:literal ),+ $(,)?) => {
        /// Signature scheme selected for block headers (node parameter
        /// `block_authentication`, CLI `--block-authentication`).
        #[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
        pub enum BlockAuthenticationScheme {
            #[default]
            #[serde(rename = "ed25519")]
            Ed25519,
            $(
                #[serde(rename = $name)]
                $variant,
            )+
        }

        impl BlockAuthenticationScheme {
            pub const ALL: &'static [Self] = &[Self::Ed25519, $( Self::$variant, )+];

            pub fn name(self) -> &'static str {
                match self {
                    Self::Ed25519 => "ed25519",
                    $( Self::$variant => <$scheme>::NAME, )+
                }
            }

            pub fn is_post_quantum(self) -> bool {
                !matches!(self, Self::Ed25519)
            }

            pub fn public_key_size(self) -> usize {
                match self {
                    Self::Ed25519 => 32,
                    $( Self::$variant => <$scheme>::PUBLIC_KEY_SIZE, )+
                }
            }

            pub fn signature_size(self) -> usize {
                match self {
                    Self::Ed25519 => crate::crypto::SIGNATURE_SIZE,
                    $( Self::$variant => <$scheme>::SIGNATURE_SIZE, )+
                }
            }

            fn wire_tag(self) -> u8 {
                match self {
                    Self::Ed25519 => 1,
                    $( Self::$variant => $tag, )+
                }
            }

            fn from_wire_tag(tag: u8) -> Option<Self> {
                match tag {
                    1 => Some(Self::Ed25519),
                    $( $tag => Some(Self::$variant), )+
                    _ => None,
                }
            }
        }

        /// Authentication proof over the block content digest, carried in the
        /// header but excluded from the block reference.
        #[derive(Clone, PartialEq, Eq)]
        pub enum BlockAuthentication {
            /// Only valid for locally constructed genesis blocks.
            None,
            Ed25519(SignatureBytes),
            $( $variant(PqSignature<$scheme>), )+
        }

        impl BlockAuthentication {
            pub fn scheme(&self) -> Option<BlockAuthenticationScheme> {
                match self {
                    Self::None => None,
                    Self::Ed25519(_) => Some(BlockAuthenticationScheme::Ed25519),
                    $( Self::$variant(_) => Some(BlockAuthenticationScheme::$variant), )+
                }
            }

            fn payload(&self) -> &[u8] {
                match self {
                    Self::None => &[],
                    Self::Ed25519(signature) => signature.as_bytes(),
                    $( Self::$variant(signature) => signature.as_bytes(), )+
                }
            }

            fn from_parts(scheme: BlockAuthenticationScheme, bytes: &[u8]) -> Result<Self, String> {
                match scheme {
                    BlockAuthenticationScheme::Ed25519 => {
                        SignatureBytes::try_from(bytes).map(Self::Ed25519)
                    }
                    $(
                        BlockAuthenticationScheme::$variant => {
                            PqSignature::<$scheme>::from_bytes(bytes).map(Self::$variant)
                        }
                    )+
                }
            }
        }

        /// Post-quantum public key of one committee member.
        #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
        pub enum BlockPublicKey {
            $(
                #[serde(rename = $name)]
                $variant(PqPublicKey<$scheme>),
            )+
        }

        impl BlockPublicKey {
            pub fn scheme(&self) -> BlockAuthenticationScheme {
                match self {
                    $( Self::$variant(_) => BlockAuthenticationScheme::$variant, )+
                }
            }

            /// `true` iff `authentication` is a valid proof of the same scheme
            /// over `digest` under this key.
            pub fn verify(
                &self,
                digest: &BlockDigest,
                authentication: &BlockAuthentication,
            ) -> bool {
                match (self, authentication) {
                    $(
                        (Self::$variant(key), BlockAuthentication::$variant(signature)) => {
                            key.verify(digest.as_array(), signature)
                        }
                    )+
                    _ => false,
                }
            }
        }

        /// Post-quantum private key of one validator.
        #[derive(Clone, Debug, Serialize, Deserialize)]
        pub enum BlockSigningKey {
            $(
                #[serde(rename = $name)]
                $variant(PqSigner<$scheme>),
            )+
        }

        impl BlockSigningKey {
            /// Deterministically derive a key for `scheme`. Returns `None` for
            /// Ed25519, which uses the validator's identity key instead.
            pub fn from_seed(scheme: BlockAuthenticationScheme, seed: &[u8; 32]) -> Option<Self> {
                match scheme {
                    BlockAuthenticationScheme::Ed25519 => None,
                    $(
                        BlockAuthenticationScheme::$variant => {
                            Some(Self::$variant(PqSigner::<$scheme>::from_seed(seed)))
                        }
                    )+
                }
            }

            pub fn scheme(&self) -> BlockAuthenticationScheme {
                match self {
                    $( Self::$variant(_) => BlockAuthenticationScheme::$variant, )+
                }
            }

            pub fn public_key(&self) -> BlockPublicKey {
                match self {
                    $( Self::$variant(key) => BlockPublicKey::$variant(key.public_key()), )+
                }
            }

            pub fn sign(&self, digest: &BlockDigest) -> BlockAuthentication {
                match self {
                    $(
                        Self::$variant(key) => {
                            BlockAuthentication::$variant(key.sign(digest.as_array()))
                        }
                    )+
                }
            }
        }
    };
}

block_authentication_schemes! {
    MlDsa44(MlDsa44, "ml-dsa-44") = 2,
    MlDsa65(MlDsa65, "ml-dsa-65") = 3,
    MlDsa87(MlDsa87, "ml-dsa-87") = 4,
    SlhDsaSha2_128s(SlhDsaSha2_128s, "slh-dsa-sha2-128s") = 5,
    SlhDsaSha2_128f(SlhDsaSha2_128f, "slh-dsa-sha2-128f") = 6,
    SlhDsaSha2_192s(SlhDsaSha2_192s, "slh-dsa-sha2-192s") = 7,
    SlhDsaSha2_192f(SlhDsaSha2_192f, "slh-dsa-sha2-192f") = 8,
    SlhDsaSha2_256s(SlhDsaSha2_256s, "slh-dsa-sha2-256s") = 9,
    SlhDsaSha2_256f(SlhDsaSha2_256f, "slh-dsa-sha2-256f") = 10,
}

impl fmt::Display for BlockAuthenticationScheme {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.name())
    }
}

impl FromStr for BlockAuthenticationScheme {
    type Err = String;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        Self::ALL
            .iter()
            .copied()
            .find(|scheme| scheme.name() == value)
            .ok_or_else(|| {
                let names: Vec<_> = Self::ALL.iter().map(|scheme| scheme.name()).collect();
                format!(
                    "unknown block authentication scheme '{value}'; expected one of: {}",
                    names.join(", ")
                )
            })
    }
}

impl fmt::Debug for BlockAuthentication {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.scheme() {
            None => f.write_str("none"),
            Some(scheme) => write!(f, "{scheme}({})", hex::encode(&self.payload()[..4])),
        }
    }
}

/// Binary: `tag || payload` as one byte string (1 byte overhead over a bare
/// signature). Human-readable: `"<scheme>:<hex>"`, or `"none"`.
impl Serialize for BlockAuthentication {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        if serializer.is_human_readable() {
            return match self.scheme() {
                None => serializer.serialize_str("none"),
                Some(scheme) => {
                    serializer.serialize_str(&format!("{scheme}:{}", hex::encode(self.payload())))
                }
            };
        }
        let tag = self.scheme().map_or(0, BlockAuthenticationScheme::wire_tag);
        let mut bytes = Vec::with_capacity(1 + self.payload().len());
        bytes.push(tag);
        bytes.extend_from_slice(self.payload());
        serializer.serialize_bytes(&bytes)
    }
}

impl<'de> Deserialize<'de> for BlockAuthentication {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        struct AuthenticationVisitor;

        impl<'de> de::Visitor<'de> for AuthenticationVisitor {
            type Value = BlockAuthentication;

            fn expecting(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
                formatter.write_str("a block authentication proof")
            }

            fn visit_bytes<E: de::Error>(self, v: &[u8]) -> Result<Self::Value, E> {
                let Some((&tag, payload)) = v.split_first() else {
                    return Err(E::custom("empty block authentication"));
                };
                if tag == 0 {
                    return if payload.is_empty() {
                        Ok(BlockAuthentication::None)
                    } else {
                        Err(E::custom("unauthenticated block carries a payload"))
                    };
                }
                let scheme = BlockAuthenticationScheme::from_wire_tag(tag)
                    .ok_or_else(|| E::custom(format!("unknown block authentication tag {tag}")))?;
                BlockAuthentication::from_parts(scheme, payload).map_err(E::custom)
            }

            fn visit_byte_buf<E: de::Error>(self, v: Vec<u8>) -> Result<Self::Value, E> {
                self.visit_bytes(&v)
            }

            fn visit_str<E: de::Error>(self, v: &str) -> Result<Self::Value, E> {
                if v == "none" {
                    return Ok(BlockAuthentication::None);
                }
                let (scheme, payload) = v
                    .split_once(':')
                    .ok_or_else(|| E::custom("expected '<scheme>:<hex>' or 'none'"))?;
                let scheme = BlockAuthenticationScheme::from_str(scheme).map_err(E::custom)?;
                let payload = hex::decode(payload)
                    .map_err(|e| E::custom(format!("invalid signature hex encoding: {e}")))?;
                BlockAuthentication::from_parts(scheme, &payload).map_err(E::custom)
            }
        }

        if deserializer.is_human_readable() {
            deserializer.deserialize_str(AuthenticationVisitor)
        } else {
            deserializer.deserialize_bytes(AuthenticationVisitor)
        }
    }
}

// ---------------------------------------------------------------------------
// Signing-side dispatch
// ---------------------------------------------------------------------------

/// Borrowed key material used to authenticate one block.
#[derive(Clone, Copy)]
pub enum BlockSigner<'a> {
    Ed25519(&'a Signer),
    PostQuantum(&'a BlockSigningKey),
}

impl BlockSigner<'_> {
    pub fn scheme(&self) -> BlockAuthenticationScheme {
        match self {
            Self::Ed25519(_) => BlockAuthenticationScheme::Ed25519,
            Self::PostQuantum(key) => key.scheme(),
        }
    }

    pub fn sign(&self, digest: &BlockDigest) -> BlockAuthentication {
        match self {
            Self::Ed25519(signer) => {
                BlockAuthentication::Ed25519(signer.sign_digest(digest.as_array()))
            }
            Self::PostQuantum(key) => key.sign(digest),
        }
    }
}

/// Verify `authentication` over `digest` for the configured `scheme`.
///
/// The Ed25519 identity key comes from the committee entry; post-quantum keys
/// come from the authority's [`BlockPublicKey`] list. A proof of a different
/// scheme than the configured one is rejected even if it would verify under
/// its own key, so a committee cannot be tricked into downgrading.
pub fn verify_block_authentication(
    scheme: BlockAuthenticationScheme,
    digest: &BlockDigest,
    authentication: &BlockAuthentication,
    ed25519_public_key: &PublicKey,
    post_quantum_public_key: Option<&BlockPublicKey>,
) -> Result<(), String> {
    if authentication.scheme() != Some(scheme) {
        return Err(format!(
            "expected {scheme} block authentication, received {authentication:?}"
        ));
    }
    let valid = match authentication {
        BlockAuthentication::None => unreachable!("checked by scheme() above"),
        BlockAuthentication::Ed25519(signature) => ed25519_public_key
            .verify_digest_signature(digest.as_array(), signature)
            .is_ok(),
        post_quantum => match post_quantum_public_key {
            Some(key) if key.scheme() == scheme => key.verify(digest, post_quantum),
            _ => {
                return Err(format!(
                    "author has no {scheme} public key in the committee"
                ));
            }
        },
    };
    if valid {
        Ok(())
    } else {
        Err(format!("{scheme} block authentication failed"))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn digest(byte: u8) -> BlockDigest {
        BlockDigest::from([byte; 32])
    }

    #[test]
    fn scheme_names_round_trip_through_serde_and_from_str() {
        for &scheme in BlockAuthenticationScheme::ALL {
            let yaml = serde_yaml::to_string(&scheme).unwrap();
            assert_eq!(yaml.trim(), scheme.name());
            let decoded: BlockAuthenticationScheme = serde_yaml::from_str(&yaml).unwrap();
            assert_eq!(decoded, scheme);
            assert_eq!(
                scheme.name().parse::<BlockAuthenticationScheme>().unwrap(),
                scheme
            );
        }
        assert!("rsa".parse::<BlockAuthenticationScheme>().is_err());
        assert_eq!(
            BlockAuthenticationScheme::default(),
            BlockAuthenticationScheme::Ed25519
        );
    }

    #[test]
    fn wire_tags_are_unique() {
        let mut tags: Vec<u8> = BlockAuthenticationScheme::ALL
            .iter()
            .map(|scheme| scheme.wire_tag())
            .collect();
        tags.sort_unstable();
        tags.dedup();
        assert_eq!(tags.len(), BlockAuthenticationScheme::ALL.len());
        assert!(!tags.contains(&0), "tag 0 is reserved for `None`");
    }

    #[test]
    fn post_quantum_schemes_sign_verify_and_reject_tampering() {
        for &scheme in BlockAuthenticationScheme::ALL {
            let Some(key) = BlockSigningKey::from_seed(scheme, &benchmark_seed(scheme, 7)) else {
                continue;
            };
            let public_key = key.public_key();
            assert_eq!(public_key.scheme(), scheme);
            let authentication = key.sign(&digest(1));
            assert_eq!(authentication.scheme(), Some(scheme));
            assert_eq!(
                authentication.payload().len(),
                scheme.signature_size(),
                "{scheme}"
            );
            assert!(public_key.verify(&digest(1), &authentication), "{scheme}");
            assert!(!public_key.verify(&digest(2), &authentication), "{scheme}");

            // Same seed → same key; different seed → different key.
            let again = BlockSigningKey::from_seed(scheme, &benchmark_seed(scheme, 7)).unwrap();
            assert_eq!(again.public_key(), public_key);
            let other = BlockSigningKey::from_seed(scheme, &benchmark_seed(scheme, 8)).unwrap();
            assert_ne!(other.public_key(), public_key);
            assert!(!other.public_key().verify(&digest(1), &authentication));

            // Deterministic signing.
            assert_eq!(key.sign(&digest(1)), authentication);
        }
    }

    #[test]
    fn key_and_signature_encodings_round_trip() {
        for &scheme in BlockAuthenticationScheme::ALL {
            let Some(key) = BlockSigningKey::from_seed(scheme, &benchmark_seed(scheme, 1)) else {
                continue;
            };
            let public_key = key.public_key();
            let authentication = key.sign(&digest(9));

            let yaml = serde_yaml::to_string(&key).unwrap();
            let decoded_key: BlockSigningKey = serde_yaml::from_str(&yaml).unwrap();
            assert_eq!(decoded_key.public_key(), public_key, "{scheme}");
            assert_eq!(decoded_key.sign(&digest(9)), authentication, "{scheme}");

            let yaml = serde_yaml::to_string(&public_key).unwrap();
            assert!(yaml.contains(scheme.name()), "{yaml}");
            let decoded: BlockPublicKey = serde_yaml::from_str(&yaml).unwrap();
            assert_eq!(decoded, public_key);
            let encoded = bincode::serialize(&public_key).unwrap();
            let decoded: BlockPublicKey = bincode::deserialize(&encoded).unwrap();
            assert_eq!(decoded, public_key);

            let encoded = bincode::serialize(&authentication).unwrap();
            assert_eq!(encoded.len(), 8 + 1 + scheme.signature_size(), "{scheme}");
            let decoded: BlockAuthentication = bincode::deserialize(&encoded).unwrap();
            assert_eq!(decoded, authentication);
            let yaml = serde_yaml::to_string(&authentication).unwrap();
            assert!(yaml.trim().starts_with(&format!("{scheme}:")), "{yaml}");
            let decoded: BlockAuthentication = serde_yaml::from_str(&yaml).unwrap();
            assert_eq!(decoded, authentication);

            // Truncated signatures are rejected at decode time.
            let mut truncated = encoded.clone();
            truncated.truncate(truncated.len() - 1);
            let payload_len = (truncated.len() - 8) as u64;
            truncated[..8].copy_from_slice(&payload_len.to_le_bytes());
            assert!(bincode::deserialize::<BlockAuthentication>(&truncated).is_err());
        }
    }

    #[test]
    fn ed25519_and_none_encodings() {
        let signer = Signer::new_for_test(1).pop().unwrap();
        let authentication = BlockSigner::Ed25519(&signer).sign(&digest(3));
        assert_eq!(
            authentication,
            BlockAuthentication::Ed25519(signer.sign_digest(&[3; 32]))
        );
        let encoded = bincode::serialize(&authentication).unwrap();
        assert_eq!(encoded.len(), 8 + 1 + crate::crypto::SIGNATURE_SIZE);
        assert_eq!(
            bincode::deserialize::<BlockAuthentication>(&encoded).unwrap(),
            authentication
        );
        let yaml = serde_yaml::to_string(&authentication).unwrap();
        assert!(yaml.trim().starts_with("ed25519:"));
        assert_eq!(
            serde_yaml::from_str::<BlockAuthentication>(&yaml).unwrap(),
            authentication
        );

        let encoded = bincode::serialize(&BlockAuthentication::None).unwrap();
        assert_eq!(encoded.len(), 8 + 1);
        assert_eq!(
            bincode::deserialize::<BlockAuthentication>(&encoded).unwrap(),
            BlockAuthentication::None
        );
        assert_eq!(
            serde_yaml::to_string(&BlockAuthentication::None)
                .unwrap()
                .trim(),
            "none"
        );
        assert!(
            bincode::deserialize::<BlockAuthentication>(&[1, 0, 0, 0, 0, 0, 0, 0, 200]).is_err()
        );
    }

    #[test]
    fn verification_requires_the_configured_scheme() {
        let signer = Signer::new_for_test(1).pop().unwrap();
        let ed_public = signer.public_key();
        let pq_key =
            BlockSigningKey::from_seed(BlockAuthenticationScheme::MlDsa65, &[5; 32]).unwrap();
        let pq_public = pq_key.public_key();

        let ed_auth = BlockSigner::Ed25519(&signer).sign(&digest(1));
        let pq_auth = BlockSigner::PostQuantum(&pq_key).sign(&digest(1));

        assert!(
            verify_block_authentication(
                BlockAuthenticationScheme::Ed25519,
                &digest(1),
                &ed_auth,
                &ed_public,
                None
            )
            .is_ok()
        );
        assert!(
            verify_block_authentication(
                BlockAuthenticationScheme::MlDsa65,
                &digest(1),
                &pq_auth,
                &ed_public,
                Some(&pq_public)
            )
            .is_ok()
        );
        // Scheme mismatch in either direction.
        assert!(
            verify_block_authentication(
                BlockAuthenticationScheme::MlDsa65,
                &digest(1),
                &ed_auth,
                &ed_public,
                Some(&pq_public)
            )
            .is_err()
        );
        assert!(
            verify_block_authentication(
                BlockAuthenticationScheme::Ed25519,
                &digest(1),
                &pq_auth,
                &ed_public,
                Some(&pq_public)
            )
            .is_err()
        );
        // Missing or wrong-scheme committee key.
        assert!(
            verify_block_authentication(
                BlockAuthenticationScheme::MlDsa65,
                &digest(1),
                &pq_auth,
                &ed_public,
                None
            )
            .is_err()
        );
        let other = BlockSigningKey::from_seed(BlockAuthenticationScheme::MlDsa44, &[5; 32])
            .unwrap()
            .public_key();
        assert!(
            verify_block_authentication(
                BlockAuthenticationScheme::MlDsa65,
                &digest(1),
                &pq_auth,
                &ed_public,
                Some(&other)
            )
            .is_err()
        );
        // Wrong digest / genesis marker.
        assert!(
            verify_block_authentication(
                BlockAuthenticationScheme::MlDsa65,
                &digest(2),
                &pq_auth,
                &ed_public,
                Some(&pq_public)
            )
            .is_err()
        );
        assert!(
            verify_block_authentication(
                BlockAuthenticationScheme::Ed25519,
                &digest(1),
                &BlockAuthentication::None,
                &ed_public,
                None
            )
            .is_err()
        );
    }

    #[test]
    fn declared_sizes_match_the_implementations() {
        for &scheme in BlockAuthenticationScheme::ALL {
            let Some(key) = BlockSigningKey::from_seed(scheme, &[1; 32]) else {
                continue;
            };
            // bincode: u32 variant tag + u64 length prefix + bytes.
            let public_key_len = bincode::serialize(&key.public_key()).unwrap().len();
            assert_eq!(public_key_len, 4 + 8 + scheme.public_key_size(), "{scheme}");
        }
    }
}
