services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=supers3cret
      - GF_SECURITY_ADMIN_PASSWORD_FILE=
      - GF_AUTH_GENERIC_OAUTH_PERSISTENT_TOKEN=true
    user: "472"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/main.yaml:ro
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml:ro
      - ./grafana/grafana-dashboard.json:/var/lib/grafana/dashboards/grafana-dashboard.json:ro
    restart: always

volumes:
  prometheus_data:
  grafana_data: