global:
  scrape_interval: 1s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'mysticeti-metrics'
    static_configs:
      - targets:
          - 'host.docker.internal:1510'
          - 'host.docker.internal:1511'
          - 'host.docker.internal:1512'
          - 'host.docker.internal:1513'
          - 'host.docker.internal:1514'
          - 'host.docker.internal:1515'
          - 'host.docker.internal:1516'
          - 'host.docker.internal:1517'
          - 'host.docker.internal:1518'
          - 'host.docker.internal:1519'
