global:
  scrape_interval: 1s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'mysticeti-metrics'
    static_configs:
      - targets:
          - 'host.docker.internal:1515'
          - 'host.docker.internal:1516'
          - 'host.docker.internal:1517'
          - 'host.docker.internal:1518'
          - 'host.docker.internal:1519'
          - 'host.docker.internal:1520'
          - 'host.docker.internal:1521'
          - 'host.docker.internal:1522'
          - 'host.docker.internal:1523'
          - 'host.docker.internal:1524'
          - 'host.docker.internal:1525'
          - 'host.docker.internal:1526'
          - 'host.docker.internal:1527'
          - 'host.docker.internal:1528'
          - 'host.docker.internal:1529'
