global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'mysticeti-metrics'
    static_configs:
      - targets:
          - 'localhost:1511'
          - 'localhost:1512'
          - 'localhost:1513'
          - 'localhost:1514'
          - 'localhost:1515'
          - 'localhost:1516'
          - 'localhost:1517'
          - 'localhost:1518'
          - 'localhost:1519'
          - 'localhost:1520'