global:
  scrape_interval: 1s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'mysticeti-metrics'
    static_configs:
      - targets:
          - 'host.docker.internal:1519'
          - 'host.docker.internal:1520'
          - 'host.docker.internal:1521'
          - 'host.docker.internal:1522'
          - 'host.docker.internal:1523'
          - 'host.docker.internal:1524'
          - 'host.docker.internal:1525'
          - 'host.docker.internal:1526'
          - 'host.docker.internal:1527'
          - 'host.docker.internal:1528'
          - 'host.docker.internal:1529'
          - 'host.docker.internal:1530'
          - 'host.docker.internal:1531'
          - 'host.docker.internal:1532'
          - 'host.docker.internal:1533'
          - 'host.docker.internal:1534'
          - 'host.docker.internal:1535'
          - 'host.docker.internal:1536'
          - 'host.docker.internal:1537'
