global:
  scrape_interval: 1s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'mysticeti-metrics'
    static_configs:
      - targets:
          - 'host.docker.internal:1504'
          - 'host.docker.internal:1505'
          - 'host.docker.internal:1506'
          - 'host.docker.internal:1507'
