global:
  scrape_interval: 1s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'mysticeti-metrics'
    static_configs:
      - targets:
          - 'host.docker.internal:1530'
          - 'host.docker.internal:1531'
          - 'host.docker.internal:1532'
          - 'host.docker.internal:1533'
          - 'host.docker.internal:1534'
          - 'host.docker.internal:1535'
          - 'host.docker.internal:1536'
          - 'host.docker.internal:1537'
          - 'host.docker.internal:1538'
          - 'host.docker.internal:1539'
          - 'host.docker.internal:1540'
          - 'host.docker.internal:1541'
          - 'host.docker.internal:1542'
          - 'host.docker.internal:1543'
          - 'host.docker.internal:1544'
          - 'host.docker.internal:1545'
          - 'host.docker.internal:1546'
          - 'host.docker.internal:1547'
          - 'host.docker.internal:1548'
          - 'host.docker.internal:1549'
          - 'host.docker.internal:1550'
          - 'host.docker.internal:1551'
          - 'host.docker.internal:1552'
          - 'host.docker.internal:1553'
          - 'host.docker.internal:1554'
          - 'host.docker.internal:1555'
          - 'host.docker.internal:1556'
          - 'host.docker.internal:1557'
          - 'host.docker.internal:1558'
          - 'host.docker.internal:1559'
