{
 "title": "Mysticeti",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "TPS (per node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(sequenced_transactions_total[1m])"
    }
   ]
  },
  {
   "title": "Latency(ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(block_committed_latency{v=\"p50\"}) / 1000",
     "legendFormat": "Block latency p50"
    },
    {
     "expr": "avg(transaction_committed_latency{v=\"p50\"}) / 1000",
     "legendFormat": "Tx Commit p50"
    }
   ]
  },
  {
   "title": "Core functions (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by(proc) (rate(utilization_timer[1m]) / 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Core thread utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(core_lock_util[1m]) / 1000000 * 100"
    }
   ]
  },
  {
   "title": "Avg connection latency (by peer)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg(connection_latency{v=\"p50\"} / 1000) by (peer)"
    }
   ]
  },
  {
   "title": "Proposed block size p50(Kbytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "proposed_block_size_bytes{v=\"p50\"} / 1024"
    }
   ]
  },
  {
   "title": "Core queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "core_lock_enqueued - core_lock_dequeued"
    }
   ]
  },
  {
   "title": "Committed Leaders (view of Node 0)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "committed_leaders_total{job=\"instance-node-0\"}",
     "legendFormat": "Node {{authority}} - {{commit_type}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1024 / 1024 /1024"
    }
   ]
  },
  {
   "title": "Network receive (Mbps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"ens5\"}[1m]) / 1024 / 1024 * 8"
    }
   ]
  },
  {
   "title": "Network sent code (Mbps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(bytes_sent_total[1m])*8/1024/1024"
    }
   ]
  },
  {
   "title": "Network received code (Mbps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "rate(bytes_received_total[1m])*8/1024/1024"
    }
   ]
  }
 ]
}